import http from 'node:http';

const PORT=Number(process.env.PORT||3000);
const EVO=String(process.env.EVOLUTION_API_URL||'').replace(/\/$/,'');
const EVO_KEY=String(process.env.EVOLUTION_API_KEY||'');
const CORE=String(process.env.BIZI_CORE_URL||'https://shftukueyostzbyqxmqw.supabase.co/functions/v1').replace(/\/$/,'');
const CORE_KEY=String(process.env.BIZI_CORE_KEY||'');
const HOOK_SECRET=String(process.env.WEBHOOK_SHARED_SECRET||'');
const TARGET_INSTANCE_ID=String(process.env.EVOLUTION_INSTANCE_ID||'');
const WEBHOOK_URL=String(process.env.WEBHOOK_URL||'');
const AUTO_CONFIGURE=String(process.env.AUTO_CONFIGURE||'false')==='true';
const RUN_SELF_TEST=String(process.env.RUN_SELF_TEST||'false')==='true';
let instanceName='';
const j=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body))};
const clean=v=>String(v??'').trim();
async function api(url,opts={}){const r=await fetch(url,opts);const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}return {ok:r.ok,status:r.status,data:d}}
function normalize(body){const d=Array.isArray(body?.data)?body.data[0]??{}:body?.data??{};const k=d.key??{};const msg=d.message??{};const event=clean(body?.event??d?.event).toLowerCase();return {event,instance_name:clean(body?.instance??d?.instanceName??d?.instance),instance_id:clean(d?.instanceId??body?.instanceId??body?.instance_id),remote_jid:clean(k?.remoteJid??d?.remoteJid),from_me:Boolean(k?.fromMe??d?.fromMe),message_id:clean(k?.id??d?.id),push_name:clean(d?.pushName??body?.pushName),message:clean(msg?.conversation??msg?.extendedTextMessage?.text??msg?.imageMessage?.caption??msg?.videoMessage?.caption??d?.text),dry_run:body?.dry_run===true};}
async function core(path,body){return api(`${CORE}/${path}`,{method:'POST',headers:{'content-type':'application/json','x-bizi-core-key':CORE_KEY},body:JSON.stringify(body)})}
async function resolveInstance(){if(!EVO||!EVO_KEY)return null;const r=await api(`${EVO}/instance/fetchInstances`,{headers:{apikey:EVO_KEY}});if(!r.ok){console.log('INSTANCE_LOOKUP_FAILED',r.status);return null}const list=Array.isArray(r.data)?r.data:(Array.isArray(r.data?.instances)?r.data.instances:[]);const row=list.find(x=>clean(x?.id??x?.instanceId??x?.instance?.instanceId)===TARGET_INSTANCE_ID)||list[0];instanceName=clean(row?.name??row?.instanceName??row?.instance?.instanceName??row?.instance?.name);console.log('INSTANCE_RESOLVED',Boolean(instanceName),instanceName||'none');return row}
async function configureWebhook(){if(!AUTO_CONFIGURE||!WEBHOOK_URL||!instanceName)return;const payload={webhook:{enabled:true,url:WEBHOOK_URL,webhookByEvents:false,events:['MESSAGES_UPSERT'],headers:{'x-bizi-webhook-secret':HOOK_SECRET}}};for(const p of [`/event/webhook/set/${encodeURIComponent(instanceName)}`,`/webhook/set/${encodeURIComponent(instanceName)}`]){const r=await api(`${EVO}${p}`,{method:'POST',headers:{apikey:EVO_KEY,'content-type':'application/json'},body:JSON.stringify(payload)});console.log('WEBHOOK_CONFIG_ATTEMPT',p,r.status);if(r.ok){console.log('WEBHOOK_CONFIGURED',instanceName,WEBHOOK_URL);return}}console.log('WEBHOOK_CONFIG_FAILED')}
async function processEvent(body,{forceDryRun=false}={}){const n=normalize(body);const isMsg=['messages.upsert','messages_upsert','messages-upsert'].includes(n.event);if(!isMsg||n.from_me||n.remote_jid.endsWith('@g.us')||n.remote_jid==='status@broadcast'||!n.message)return {accepted:false,reason:'ignored_event'};const iid=n.instance_id||TARGET_INSTANCE_ID;if(!iid)return {accepted:false,reason:'instance_id_missing'};const route=await core('bizi-core-router',{action:'resolve_channel',provider:'evolution_api',external_instance_id:iid});if(!route.ok||!route.data?.ok)return {accepted:false,reason:'channel_not_found',route_status:route.status};const ch=route.data.channel;const proc=await core('bizi-core-whatsapp',{action:'process_inbound',client_key:route.data.client_key,channel_id:ch.id,remote_jid:n.remote_jid,message:n.message,message_id:n.message_id,push_name:n.push_name,instance_name:n.instance_name||instanceName,is_demo:ch?.config?.is_demo===true});if(!proc.ok||!proc.data?.ok)return {accepted:true,processed:false,error:proc.data?.error||'core_failed',status:proc.status};const dry=forceDryRun||n.dry_run;if(proc.data.send===true&&!dry){const name=n.instance_name||instanceName;if(!name)return {accepted:true,processed:true,sent:false,error:'instance_name_missing',result:proc.data};const number=n.remote_jid.replace(/@s\.whatsapp\.net$/,'');const send=await api(`${EVO}/message/sendText/${encodeURIComponent(name)}`,{method:'POST',headers:{apikey:EVO_KEY,'content-type':'application/json'},body:JSON.stringify({number,text:proc.data.reply})});if(!send.ok)return {accepted:true,processed:true,sent:false,error:'evolution_send_failed',send_status:send.status,result:proc.data};const outId=clean(send.data?.key?.id??send.data?.data?.key?.id??send.data?.message?.key?.id)||`out-${n.message_id}-${Date.now()}`;await core('bizi-core-whatsapp',{action:'record_outbound',client_key:proc.data.client_key,channel_id:proc.data.channel_id,outbound_message_id:outId,remote_jid:n.remote_jid,reply:proc.data.reply,source_inbound_id:proc.data.source_inbound_id});return {accepted:true,processed:true,sent:true,result:proc.data}}
return {accepted:true,processed:true,sent:false,dry_run:dry,result:proc.data}}
async function selfTest(){if(!RUN_SELF_TEST)return;const id=`bizi-selftest-${Date.now()}`;const body={event:'messages.upsert',instance:instanceName||'favfare-selftest',dry_run:true,data:{instanceId:TARGET_INSTANCE_ID,key:{remoteJid:'2348000000999@s.whatsapp.net',fromMe:false,id},pushName:'Bizi Gateway Self Test',message:{conversation:'hello'}}};const r=await processEvent(body,{forceDryRun:true});console.log('SELF_TEST_RESULT',JSON.stringify({ok:r?.accepted===true&&r?.processed===true,sent:r?.sent,dry_run:r?.dry_run,error:r?.error||null,message_id:id}));}
const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/health')return j(res,200,{ok:true,service:'bizi-whatsapp-gateway',instance_resolved:Boolean(instanceName)});if(req.method!=='POST'||!req.url?.startsWith('/webhook/evolution'))return j(res,404,{ok:false,error:'not_found'});if(HOOK_SECRET&&req.headers['x-bizi-webhook-secret']!==HOOK_SECRET)return j(res,401,{ok:false,error:'unauthorized'});let raw='';for await(const c of req)raw+=c;let body;try{body=JSON.parse(raw||'{}')}catch{return j(res,400,{ok:false,error:'invalid_json'})}const result=await processEvent(body);return j(res,200,{ok:true,...result})}catch(e){console.error('REQUEST_ERROR',e?.message);return j(res,500,{ok:false,error:'internal_error'})}});
server.listen(PORT,'0.0.0.0',async()=>{console.log('GATEWAY_READY',PORT);await resolveInstance();await selfTest();await configureWebhook();});
