import http from 'node:http';
import crypto from 'node:crypto';

const PORT=Number(process.env.PORT||3000);
const CORE=String(process.env.BIZI_CORE_URL||'').replace(/\/$/,'');
const CORE_KEY=String(process.env.BIZI_CORE_KEY||'');
const META_TOKEN=String(process.env.META_ACCESS_TOKEN||'');
const META_PHONE_ID=String(process.env.META_PHONE_NUMBER_ID||'');
const META_WABA_ID=String(process.env.META_WABA_ID||'');
const META_VERIFY_TOKEN=String(process.env.META_VERIFY_TOKEN||'');
const META_APP_SECRET=String(process.env.META_APP_SECRET||'');
const META_REQUIRE_SIGNATURE=String(process.env.META_REQUIRE_SIGNATURE||'true')!=='false';
const GRAPH_VERSION=String(process.env.META_GRAPH_VERSION||'v26.0');
const TEST_RECIPIENT=String(process.env.META_TEST_RECIPIENT||'').replace(/\D/g,'');
const RUN_BUTTON_TEST=String(process.env.RUN_META_BUTTON_TEST||'false')==='true';
if(!CORE||!CORE_KEY)throw new Error('Bizi Core configuration required');

const clean=v=>String(v??'').trim(),digits=v=>clean(v).replace(/\D/g,'');
const security={'cache-control':'no-store','x-robots-tag':'noindex, nofollow','x-content-type-options':'nosniff','referrer-policy':'no-referrer'};
const json=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json',...security});res.end(JSON.stringify(body))};
const text=(res,status,body)=>{res.writeHead(status,{'content-type':'text/plain; charset=utf-8',...security});res.end(String(body))};
async function readBody(req,max=1048576){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max){const e=new Error('body_too_large');e.status=413;throw e}chunks.push(c)}return Buffer.concat(chunks)}
function signatureOk(req,raw){if(META_REQUIRE_SIGNATURE&&!META_APP_SECRET)return false;if(!META_APP_SECRET)return true;const supplied=clean(req.headers['x-hub-signature-256']);if(!supplied.startsWith('sha256='))return false;const expected='sha256='+crypto.createHmac('sha256',META_APP_SECRET).update(raw).digest('hex');try{const a=Buffer.from(supplied),b=Buffer.from(expected);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
async function api(url,opts={}){const r=await fetch(url,opts),body=await r.text();let data;try{data=body?JSON.parse(body):null}catch{data=body}return {ok:r.ok,status:r.status,data}}
async function core(path,body){return api(`${CORE}/${path}`,{method:'POST',headers:{'content-type':'application/json','x-bizi-core-key':CORE_KEY},body:JSON.stringify(body)})}
async function subscribeWaba(){if(!META_TOKEN||!META_WABA_ID)return {ok:false,status:409,data:{error:'meta_waba_credentials_missing'}};return api(`https://graph.facebook.com/${encodeURIComponent(GRAPH_VERSION)}/${encodeURIComponent(META_WABA_ID)}/subscribed_apps`,{method:'POST',headers:{Authorization:`Bearer ${META_TOKEN}`,'content-type':'application/json'}})}
function parseInbound(payload){const value=payload?.entry?.[0]?.changes?.[0]?.value,meta=value?.metadata||{},msg=value?.messages?.[0];if(!msg)return null;let message='',interactive=null;if(msg.type==='text')message=clean(msg.text?.body);else if(msg.type==='button')message=clean(msg.button?.text||msg.button?.payload);else if(msg.type==='interactive'){const br=msg.interactive?.button_reply,lr=msg.interactive?.list_reply;if(br){message=clean(br.title||br.id);interactive={type:'button_reply',id:clean(br.id),title:clean(br.title)}}else if(lr){message=clean(lr.title||lr.id);interactive={type:'list_reply',id:clean(lr.id),title:clean(lr.title),description:clean(lr.description)}}}if(!message)return null;return {phone_number_id:clean(meta.phone_number_id),display_phone_number:clean(meta.display_phone_number),remote:digits(msg.from),message_id:clean(msg.id),message,interactive,profile_name:clean(value?.contacts?.[0]?.profile?.name),raw_type:clean(msg.type)}}
function optionId(choice,index){const base=clean(choice?.slug||choice?.value||choice?.date||choice?.time||choice?.label||`option_${index+1}`).toLowerCase().replace(/[^a-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,200);return base||`option_${index+1}`}
async function sendMeta({to,textBody,choices=[]}){if(!META_TOKEN||!META_PHONE_ID)return {ok:false,status:409,data:{error:'meta_credentials_missing'}};const usable=Array.isArray(choices)?choices.filter(c=>clean(c?.label)).slice(0,10):[];let body;if(usable.length&&usable.length<=3)body={messaging_product:'whatsapp',recipient_type:'individual',to:digits(to),type:'interactive',interactive:{type:'button',body:{text:clean(textBody)||'Choose an option'},action:{buttons:usable.map((c,i)=>({type:'reply',reply:{id:optionId(c,i),title:clean(c.label).slice(0,20)}}))}}};else if(usable.length>3)body={messaging_product:'whatsapp',recipient_type:'individual',to:digits(to),type:'interactive',interactive:{type:'list',body:{text:clean(textBody)||'Choose an option'},action:{button:'View options',sections:[{title:'Options',rows:usable.map((c,i)=>({id:optionId(c,i),title:clean(c.label).slice(0,24),description:clean(c.description).slice(0,72)}))}]}}};else body={messaging_product:'whatsapp',recipient_type:'individual',to:digits(to),type:'text',text:{preview_url:false,body:clean(textBody)}};return api(`https://graph.facebook.com/${encodeURIComponent(GRAPH_VERSION)}/${encodeURIComponent(META_PHONE_ID)}/messages`,{method:'POST',headers:{Authorization:`Bearer ${META_TOKEN}`,'content-type':'application/json'},body:JSON.stringify(body)})}
async function processMeta(payload){const n=parseInbound(payload);if(!n)return {accepted:false,reason:'no_supported_message'};const route=await core('bizi-core-router',{action:'resolve_channel',provider:'meta_cloud_api',external_instance_id:n.phone_number_id});if(!route.ok||!route.data?.ok)return {accepted:true,processed:false,reason:'channel_not_found'};const ch=route.data.channel,proc=await core('bizi-core-whatsapp',{action:'process_inbound',client_key:route.data.client_key,channel_id:ch.id,remote_jid:n.remote,message:n.message,message_id:n.message_id,push_name:n.profile_name,instance_name:n.phone_number_id});if(!proc.ok||!proc.data?.ok)return {accepted:true,processed:false,error:proc.data?.error||'core_failed'};let sent=false,sendStatus=null,outId=null;if(proc.data.send===true&&clean(proc.data.reply)){const pre=await core('bizi-core-whatsapp',{action:'pre_send_check',client_key:proc.data.client_key,channel_id:proc.data.channel_id,enquiry_id:proc.data.enquiry_id,remote_jid:n.remote});if(!pre.ok||pre.data?.allowed!==true)return {accepted:true,processed:true,sent:false,reason:'pre_send_blocked',result:proc.data};const s=await sendMeta({to:n.remote,textBody:proc.data.reply,choices:proc.data.choices||[]});sendStatus=s.status;if(s.ok){sent=true;outId=clean(s.data?.messages?.[0]?.id)||`meta-out-${Date.now()}`;await core('bizi-core-whatsapp',{action:'record_outbound',client_key:proc.data.client_key,channel_id:proc.data.channel_id,outbound_message_id:outId,remote_jid:n.remote,reply:proc.data.reply,source_inbound_id:proc.data.source_inbound_id||null})}}return {accepted:true,processed:true,sent,send_status:sendStatus,outbound_message_id:outId,result:proc.data,interactive:n.interactive}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,service:'bizi-meta-whatsapp-gateway',version:3,signature_required:META_REQUIRE_SIGNATURE,configured:Boolean(META_TOKEN&&META_PHONE_ID&&META_WABA_ID&&META_VERIFY_TOKEN&&(!META_REQUIRE_SIGNATURE||META_APP_SECRET))});if(req.method==='GET'&&u.pathname==='/webhook/meta'){if(!META_VERIFY_TOKEN)return text(res,503,'Webhook verification is not configured');const mode=u.searchParams.get('hub.mode'),token=u.searchParams.get('hub.verify_token'),challenge=u.searchParams.get('hub.challenge');return mode==='subscribe'&&token===META_VERIFY_TOKEN&&challenge?text(res,200,challenge):text(res,403,'Forbidden')}if(req.method==='POST'&&u.pathname==='/webhook/meta'){const raw=await readBody(req);if(!signatureOk(req,raw))return text(res,401,'Invalid signature');let payload;try{payload=JSON.parse(raw.toString('utf8'))}catch{return json(res,400,{ok:false,error:'invalid_json'})}const result=await processMeta(payload);console.log('META_WEBHOOK_RESULT',JSON.stringify({accepted:result.accepted,processed:result.processed,sent:result.sent,send_status:result.send_status,reason:result.reason||null}));return json(res,200,{ok:true})}return json(res,404,{ok:false,error:'not_found'})}catch(e){console.error('META_GATEWAY_ERROR',e?.message||e);return json(res,e?.status===413?413:500,{ok:false,error:e?.status===413?'body_too_large':'internal_error'})}});
server.listen(PORT,'0.0.0.0',()=>{console.log('BIZI_META_GATEWAY_READY',PORT,JSON.stringify({configured:Boolean(META_TOKEN&&META_PHONE_ID&&META_WABA_ID),signature_required:META_REQUIRE_SIGNATURE}));if(META_TOKEN&&META_WABA_ID)setTimeout(async()=>{const r=await subscribeWaba();console.log('META_WABA_SUBSCRIBE_RESULT',JSON.stringify({ok:r.ok,status:r.status,success:r.data?.success===true}))},2000);if(RUN_BUTTON_TEST&&TEST_RECIPIENT)setTimeout(async()=>{const r=await sendMeta({to:TEST_RECIPIENT,textBody:'Bizi WhatsApp integration test',choices:[{label:'View services',value:'view_services'},{label:'Book appointment',value:'book_appointment'},{label:'Talk to staff',value:'talk_to_staff'}]});console.log('META_BUTTON_TEST_RESULT',JSON.stringify({ok:r.ok,status:r.status,message_id:clean(r.data?.messages?.[0]?.id)||null}))},5000)});
