import http from 'node:http';
import { URL } from 'node:url';

const PORT=Number(process.env.PORT||3000);
const CORE_BASE=String(process.env.BIZI_CORE_URL||'https://shftukueyostzbyqxmqw.supabase.co/functions/v1').replace(/\/$/,'');
const CORE_KEY=String(process.env.BIZI_CORE_KEY||'');
const GROQ_KEY=String(process.env.GROQ_API_KEY||'');
const CLIENT_KEY=String(process.env.CLIENT_KEY||'favfare').trim();
const PACKAGE=String(process.env.DEMO_PACKAGE||'package2').trim().toLowerCase();

const send=(res,status,body,type='application/json; charset=utf-8')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});res.end(type.startsWith('application/json')?JSON.stringify(body):body)};
const readJson=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1_000_000){req.destroy();reject(new Error('body_too_large'))}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(new Error('invalid_json'))}});req.on('error',reject)});
async function core(fn,body){if(!CORE_KEY)throw new Error('core_key_missing');const headers={'content-type':'application/json','x-bizi-core-key':CORE_KEY};if(GROQ_KEY)headers['x-groq-key']=GROQ_KEY;const r=await fetch(`${CORE_BASE}/${fn}`,{method:'POST',headers,body:JSON.stringify({client_key:CLIENT_KEY,is_demo:true,...body})});const t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{d={ok:false,error:'invalid_core_response',raw:t.slice(0,300)}};if(!r.ok||d?.ok===false){const e=new Error(d?.error||`core_${r.status}`);e.status=r.status;e.payload=d;throw e}return d}
const features=()=>({package:PACKAGE,follow_up_engine:PACKAGE!=='basic'&&PACKAGE!=='package1',booking_controls:PACKAGE!=='basic'&&PACKAGE!=='package1',human_handoff:true,presentation_mode:true});

async function api(req,res,url){
  try{
    if(req.method==='GET'&&url.pathname==='/api/config'){const d=await core('bizi-core-crm',{action:'client_config'});return send(res,200,{...d,features:features()})}
    if(req.method==='GET'&&url.pathname==='/api/overview')return send(res,200,await core('bizi-core-crm',{action:'overview'}));
    if(req.method==='GET'&&url.pathname==='/api/enquiries')return send(res,200,await core('bizi-core-crm',{action:'list_enquiries',limit:80}));
    if(req.method==='GET'&&url.pathname==='/api/catalogue')return send(res,200,await core('bizi-core-data',{action:'catalogue'}));
    if(req.method==='POST'&&url.pathname==='/api/detail'){const b=await readJson(req);return send(res,200,await core('bizi-core-crm',{action:'enquiry_detail',enquiry_id:b.enquiry_id}))}
    if(req.method==='POST'&&url.pathname==='/api/action'){const b=await readJson(req);return send(res,200,await core('bizi-core-crm',{action:'staff_action',...b}))}
    if(req.method==='POST'&&url.pathname==='/api/reset'){return send(res,200,await core('bizi-core-demo-admin',{action:'reset_and_seed'}))}
    if(req.method==='POST'&&url.pathname==='/api/chat'){
      const b=await readJson(req),sessionId=String(b.session_id||'').trim();if(!sessionId)return send(res,400,{ok:false,error:'session_id_required'});
      let context=b.context&&typeof b.context==='object'?{...b.context}:{},preCaptured=false;
      if(b.service_slug){const q=await core('bizi-core-data',{action:'quote_and_capture',service_slug:String(b.service_slug),session_id:sessionId,whatsapp_id:`webdemo:${sessionId}`,full_name:'Demo Patient',message:String(b.message||'')});if(q?.service){context.service_slug=q.service.slug;context.service_name=q.service.name;preCaptured=true}}
      let d=await core('bizi-core-assistant',{action:'chat',session_id:sessionId,message:String(b.message||''),history:Array.isArray(b.history)?b.history.slice(-18):[],context});
      if(d?.context?.service_slug&&!preCaptured){await core('bizi-core-data',{action:'quote_and_capture',service_slug:d.context.service_slug,session_id:sessionId,whatsapp_id:`webdemo:${sessionId}`,full_name:d.context.full_name||'Demo Patient',message:String(b.message||'')});if(d.provider==='booking_flow')d=await core('bizi-core-assistant',{action:'chat',session_id:sessionId,message:String(b.message||''),history:Array.isArray(b.history)?b.history.slice(-18):[],context:d.context||context})}
      return send(res,200,d)
    }
    return send(res,404,{ok:false,error:'not_found'});
  }catch(e){console.error('API_ERROR',url.pathname,e?.message);return send(res,Number(e?.status)||500,{ok:false,error:e?.message||'internal_error',detail:e?.payload||null})}
}

const sharedCss=`
:root{--accent:#26705b;--surface:#fffdfa;--ink:#14231f;--muted:#65736e;--line:#dce4e0;--bg:#eef3f0;--danger:#b33b3b;--warn:#9a6a08;--shadow:0 18px 55px rgba(18,52,42,.12)}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:var(--bg)}button,input,textarea,select{font:inherit}button{cursor:pointer}.hidden{display:none!important}.toast{position:fixed;right:18px;top:18px;z-index:90;max-width:min(420px,calc(100vw - 36px));padding:13px 16px;border-radius:14px;background:#15251f;color:white;box-shadow:var(--shadow);opacity:0;transform:translateY(-8px);pointer-events:none;transition:.2s}.toast.show{opacity:1;transform:none}.spinner{width:18px;height:18px;border:2px solid rgba(255,255,255,.4);border-top-color:white;border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.pill{display:inline-flex;align-items:center;gap:7px;padding:6px 10px;border-radius:999px;background:#e6f1ed;color:#17614e;font-size:12px;font-weight:750}.btn{border:0;border-radius:12px;padding:10px 14px;font-weight:760;background:var(--accent);color:white}.btn.secondary{background:white;color:var(--ink);border:1px solid var(--line)}.btn.danger{background:#fff0f0;color:var(--danger);border:1px solid #f0c9c9}.muted{color:var(--muted)}
`;

function patientPage(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bizi Patient Demo</title><style>${sharedCss}
body{min-height:100vh}.wrap{min-height:100vh;display:grid;grid-template-columns:minmax(310px,1fr) minmax(360px,760px);gap:54px;align-items:center;max-width:1500px;margin:auto;padding:44px}.intro{max-width:620px}.eyebrow{letter-spacing:.16em;font-weight:850;color:var(--accent);font-size:13px}.intro h1{font-size:clamp(42px,5vw,76px);line-height:.98;margin:18px 0 26px}.intro p{font-size:20px;line-height:1.65;color:var(--muted)}.intro a{display:inline-block;margin-top:18px;color:var(--accent);font-weight:800;text-decoration:none}.phone{background:#f7f4ef;border-radius:38px;overflow:hidden;box-shadow:var(--shadow);min-height:780px;display:flex;flex-direction:column;border:1px solid rgba(255,255,255,.8)}.head{background:var(--accent);color:white;padding:24px 26px;display:flex;align-items:center;gap:14px}.avatar{width:54px;height:54px;border-radius:50%;background:white;color:var(--accent);display:grid;place-items:center;font-weight:900;font-size:24px}.head strong{font-size:23px}.sandbox{background:#fff2bd;color:#795914;text-align:center;padding:10px;font-size:14px}.messages{padding:24px;display:flex;flex-direction:column;gap:12px;overflow:auto;flex:1;min-height:360px}.bubble{max-width:82%;padding:13px 16px;border-radius:16px;line-height:1.45;white-space:pre-wrap}.assistant{align-self:flex-start;background:white;box-shadow:0 3px 12px rgba(0,0,0,.06)}.patient{align-self:flex-end;background:#d9f3e9}.typing{display:flex;gap:6px;align-items:center}.typing i{width:7px;height:7px;background:#8a9893;border-radius:50%;animation:pulse 1s infinite}.typing i:nth-child(2){animation-delay:.15s}.typing i:nth-child(3){animation-delay:.3s}@keyframes pulse{0%,100%{opacity:.25}50%{opacity:1}}.choices{display:grid;gap:8px;margin:0 20px 10px}.choice{background:white;border:1px solid var(--line);border-radius:13px;text-align:left;padding:12px 14px;color:var(--accent);font-weight:780}.choice small{display:block;color:var(--muted);font-weight:500;margin-top:3px}.quick{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:0 20px 12px}.quick button{background:#f7fbf9;border:1px solid var(--line);padding:10px;border-radius:11px;color:var(--accent);font-weight:720}.composer{display:flex;gap:10px;padding:16px 20px 22px;background:#f2f5f4}.composer input{flex:1;border:1px solid var(--line);border-radius:999px;padding:14px 18px;outline:none;background:white}.composer input:focus{border-color:var(--accent)}.send{width:50px;height:50px;border-radius:50%;border:0;background:#09aa7c;color:white;font-size:20px;display:grid;place-items:center}.handoff{margin:0 20px 12px;padding:10px 12px;border-radius:12px;background:#fff2db;color:#825510;font-size:13px;font-weight:700}
@media(max-width:900px){.wrap{display:block;padding:0;max-width:none}.intro{display:none}.phone{border-radius:0;min-height:100vh;box-shadow:none}.head{padding:18px}.sandbox{font-size:12px}.messages{padding:18px}.quick{grid-template-columns:1fr}.composer{position:sticky;bottom:0}.choice{padding:11px 13px}}
</style></head><body><div id="toast" class="toast"></div><main class="wrap"><section class="intro"><div class="eyebrow">BIZI SYSTEMS · CLIENT DEMO</div><h1 id="hero">Patient Assistant</h1><p>A conversation-first WhatsApp receptionist sandbox for service questions, structured enquiry capture, safe booking and human handoff.</p><a href="/crm">Open staff CRM →</a></section><section class="phone"><header class="head"><div class="avatar" id="avatar">F</div><div><strong id="clinic">Client Clinic</strong><div style="opacity:.78;margin-top:3px">online</div></div></header><div class="sandbox">Sandbox · synthetic demo data only</div><div class="messages" id="messages"></div><div id="handoff" class="handoff hidden">A staff member should continue this conversation.</div><div id="choices" class="choices"></div><div class="quick"><button data-q="I'd like to book an appointment">Book appointment</button><button data-q="Show me your services and prices">Services & prices</button><button data-q="I have a question">Make an enquiry</button></div><form class="composer" id="form"><input id="input" autocomplete="off" placeholder="Message"><button class="send" id="send" aria-label="Send">➤</button></form></section></main><script>
const $=s=>document.querySelector(s),messages=$('#messages'),choices=$('#choices'),toast=$('#toast');let history=[],context={},busy=false;const sid=sessionStorage.biziDemoSession||(sessionStorage.biziDemoSession='web-'+Date.now()+'-'+Math.random().toString(16).slice(2));
function note(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}function bubble(who,text){const d=document.createElement('div');d.className='bubble '+(who==='patient'?'patient':'assistant');d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}function typing(on){let d=$('#typing');if(on&&!d){d=document.createElement('div');d.id='typing';d.className='bubble assistant typing';d.innerHTML='<i></i><i></i><i></i>';messages.appendChild(d);messages.scrollTop=messages.scrollHeight}else if(!on&&d)d.remove()}
function renderChoices(d){choices.innerHTML='';const arr=[...(d.choices||[]),...(d.menu_choices||[])];for(const c of arr){const b=document.createElement('button');b.className='choice';const label=c.label||c.name||c.date||c.time||'Select';b.textContent=label;if(c.description){const s=document.createElement('small');s.textContent=c.description;b.appendChild(s)}b.onclick=()=>{const patch={};if(c.date)patch.selected_date=c.date;if(c.time)patch.selected_time=c.time;const booking=String(d.intent||'').startsWith('booking')||d.provider==='booking_flow';send(booking&&c.slug?'Book '+label:label,patch,c.slug||null)};choices.appendChild(b)}}
async function send(text,patch={},slug=null){if(busy||!text.trim())return;busy=true;Object.assign(context,patch);bubble('patient',text);history.push({who:'patient',text});$('#input').value='';choices.innerHTML='';$('#handoff').classList.add('hidden');typing(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:sid,message:text,history:history.slice(-18),context,service_slug:slug})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Message failed');context=d.context||context;typing(false);if(d.reply){bubble('assistant',d.reply);history.push({who:'assistant',text:d.reply})}if(d.handoff)$('#handoff').classList.remove('hidden');renderChoices(d)}catch(e){typing(false);note(e.message||'Something went wrong');bubble('assistant','I had trouble loading that. Please try again.')}finally{busy=false}}
$('#form').onsubmit=e=>{e.preventDefault();send($('#input').value)};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>send(b.dataset.q));
(async()=>{try{const r=await fetch('/api/config'),d=await r.json(),c=d.client||{},br=c.branding||{};document.documentElement.style.setProperty('--accent',br.accent||'#26705b');const name=c.display_name||br.brand_name||'Client Clinic';$('#clinic').textContent=name;$('#hero').textContent=(br.brand_name||name)+' Patient Assistant';$('#avatar').textContent=(br.brand_name||name).trim().charAt(0).toUpperCase();document.title=(br.brand_name||name)+' Patient Assistant';bubble('assistant','Hi 👋 Welcome to '+(br.brand_name||name)+'. How can I help you today?')}catch{bubble('assistant','Hi 👋 How can I help you today?')}})();
</script></body></html>`}

function crmPage(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bizi Staff CRM</title><style>${sharedCss}
body{min-height:100vh}.app{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.side{position:sticky;top:0;height:100vh;background:#12251f;color:white;padding:24px 18px;display:flex;flex-direction:column}.brand{font-weight:900;font-size:21px;padding:8px 10px 26px}.nav{display:grid;gap:7px}.nav button,.nav a{border:0;background:transparent;color:#cfe0da;text-decoration:none;text-align:left;padding:12px;border-radius:11px;font-weight:720}.nav .active{background:rgba(255,255,255,.11);color:white}.side .bottom{margin-top:auto}.main{padding:32px;min-width:0}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:26px}.top h1{margin:0;font-size:30px}.actions{display:flex;gap:9px;flex-wrap:wrap}.metrics{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:14px;margin-bottom:22px}.metric{background:white;border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 6px 24px rgba(18,52,42,.05)}.metric .n{font-size:31px;font-weight:900;margin-top:8px}.grid{display:grid;grid-template-columns:minmax(360px,1.2fr) minmax(320px,.8fr);gap:18px}.panel{background:white;border:1px solid var(--line);border-radius:18px;overflow:hidden;min-width:0}.panelhead{padding:17px 18px;border-bottom:1px solid var(--line);font-weight:850;display:flex;justify-content:space-between;align-items:center}.rows{max-height:70vh;overflow:auto}.row{padding:14px 18px;border-bottom:1px solid #eef2f0;cursor:pointer;display:grid;grid-template-columns:minmax(140px,1fr) 130px 110px;gap:10px;align-items:center}.row:hover,.row.selected{background:#f3f8f6}.row strong{display:block}.status{font-size:11px;font-weight:850;text-transform:uppercase;letter-spacing:.06em;padding:5px 8px;border-radius:999px;background:#eef4f1;width:max-content}.status.human{background:#fff0de;color:#89560b}.status.booked{background:#e7f5eb;color:#276a39}.detail{padding:18px}.empty{padding:46px 20px;text-align:center;color:var(--muted)}.detail h2{margin:0 0 4px}.kv{display:grid;grid-template-columns:110px 1fr;gap:8px;margin:18px 0;font-size:14px}.kv span:nth-child(odd){color:var(--muted)}.detail-actions{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.timeline{margin-top:20px;border-top:1px solid var(--line);padding-top:14px}.event{padding:10px 0;border-bottom:1px solid #eef2f0;font-size:13px}.event strong{display:block;margin-bottom:3px}.loader{position:fixed;inset:0;background:rgba(238,243,240,.68);display:grid;place-items:center;z-index:80}.loader .box{background:#173029;color:white;border-radius:15px;padding:14px 18px;display:flex;gap:10px;align-items:center}.mobilebar{display:none}
@media(max-width:1050px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.rows{max-height:44vh}}@media(max-width:720px){.app{display:block}.side{display:none}.mobilebar{display:flex;position:sticky;top:0;z-index:30;background:#12251f;color:white;padding:12px 14px;align-items:center;justify-content:space-between}.mobilebar a{color:white;text-decoration:none;font-weight:800}.main{padding:16px}.top{align-items:flex-start}.top h1{font-size:24px}.metrics{grid-template-columns:1fr 1fr;gap:9px}.metric{padding:13px}.metric .n{font-size:25px}.row{grid-template-columns:minmax(120px,1fr) 90px}.row>div:nth-child(3){display:none}.panel{border-radius:14px}.actions .btn.secondary{display:none}.detail-actions .btn{flex:1 1 45%}}
</style></head><body><div id="toast" class="toast"></div><div id="loader" class="loader"><div class="box"><span class="spinner"></span>Loading demo…</div></div><div class="mobilebar"><strong id="mbrand">Bizi CRM</strong><a href="/patient">Patient demo →</a></div><div class="app"><aside class="side"><div class="brand" id="brand">Bizi Systems</div><nav class="nav"><button class="active">Overview & Enquiries</button><a href="/patient">Patient simulator ↗</a></nav><div class="bottom"><div class="pill">● Presentation mode</div></div></aside><main class="main"><header class="top"><div><div class="muted" style="font-size:13px;font-weight:750">PATIENT OPERATIONS</div><h1 id="title">Staff CRM</h1></div><div class="actions"><button id="reset" class="btn secondary">Reset demo</button><a class="btn" style="text-decoration:none" href="/patient">Open patient demo</a></div></header><section class="metrics" id="metrics"></section><section class="grid"><div class="panel"><div class="panelhead">Enquiries <span class="muted" id="count"></span></div><div class="rows" id="rows"></div></div><div class="panel"><div class="panelhead">Enquiry detail</div><div id="detail" class="empty">Select an enquiry to inspect its state and activity.</div></div></section></main></div><script>
const $=s=>document.querySelector(s),toast=$('#toast'),loader=$('#loader');let config={},selected=null,enquiries=[];function note(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function when(v){if(!v)return'—';try{return new Date(v).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}catch{return v}}async function j(url,opt){const r=await fetch(url,opt);const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Request failed');return d}
function metrics(m){const items=[['New / open',m.new_or_open||0],['Booking requests',m.booking_requests||0],['Needs human',m.needs_human||0],['Follow-up due',m.followups_due||0]];$('#metrics').innerHTML=items.map(x=>'<div class="metric"><div class="muted">'+esc(x[0])+'</div><div class="n">'+x[1]+'</div></div>').join('')}
function rows(){const el=$('#rows');$('#count').textContent=enquiries.length+' total';if(!enquiries.length){el.innerHTML='<div class="empty">No demo enquiries yet. Use Reset demo to seed presentation data.</div>';return}el.innerHTML=enquiries.map(e=>{const human=['needs_human','human_active'].includes(e.attention_status),booked=e.booking_status==='confirmed';return '<div class="row '+(selected===e.id?'selected':'')+'" data-id="'+e.id+'"><div><strong>'+esc(e.contact?.full_name||'Patient')+'</strong><span class="muted">'+esc(e.service?.name||'General enquiry')+'</span></div><div><span class="status '+(human?'human':booked?'booked':'')+'">'+esc(human?'Needs human':e.booking_status!=='none'?e.booking_status:e.status)+'</span></div><div class="muted">'+esc(e.next_action||'—')+'</div></div>'}).join('');el.querySelectorAll('[data-id]').forEach(r=>r.onclick=()=>openDetail(r.dataset.id))}
async function openDetail(id){selected=id;rows();$('#detail').innerHTML='<div class="empty">Loading…</div>';try{const d=await j('/api/detail',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enquiry_id:id})}),e=d.enquiry,a=d.activities||[];const paused=e.automation_paused===true,feat=config.features||{};let buttons='<button class="btn" data-act="'+(paused?'return_to_assistant':'take_over')+'">'+(paused?'Return to Assistant':'Take Over')+'</button><button class="btn secondary" data-act="mark_contacted">Mark contacted</button><button class="btn danger" data-act="close">Close</button>';if(feat.follow_up_engine)buttons+='<button class="btn secondary" data-follow="1">Set follow-up</button>';$('#detail').className='detail';$('#detail').innerHTML='<h2>'+esc(e.contact?.full_name||'Patient')+'</h2><div class="muted">'+esc(e.service?.name||'General enquiry')+'</div><div class="kv"><span>Status</span><b>'+esc(e.status)+'</b><span>Booking</span><b>'+esc(e.booking_status)+'</b><span>Attention</span><b>'+esc(e.attention_status)+'</b><span>Phone</span><b>'+esc(e.contact?.phone||'—')+'</b><span>Preferred</span><b>'+esc((e.preferred_date||'')+' '+(e.preferred_time_window||''))+'</b><span>Next action</span><b>'+esc(e.next_action||'—')+'</b></div><p>'+esc(e.conversation_summary||'No summary yet.')+'</p><div class="detail-actions">'+buttons+'</div><div class="timeline"><strong>Activity</strong>'+a.slice(0,20).map(x=>'<div class="event"><strong>'+esc(String(x.event_type||'').replaceAll('_',' '))+'</strong><span class="muted">'+when(x.created_at)+'</span></div>').join('')+'</div>';$('#detail').querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(id,b.dataset.act));const f=$('#detail').querySelector('[data-follow]');if(f)f.onclick=()=>follow(id)}catch(e){note(e.message);$('#detail').innerHTML='<div class="empty">Could not load this enquiry.</div>'}}
async function act(id,type){loader.classList.remove('hidden');try{await j('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enquiry_id:id,action_type:type})});await load();await openDetail(id)}catch(e){note(e.message)}finally{loader.classList.add('hidden')}}async function follow(id){const dt=new Date(Date.now()+24*3600000).toISOString();loader.classList.remove('hidden');try{await j('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enquiry_id:id,action_type:'set_follow_up',follow_up_due_at:dt,note:'Follow up with patient'})});await load();await openDetail(id);note('Follow-up scheduled for tomorrow')}catch(e){note(e.message)}finally{loader.classList.add('hidden')}}
async function load(){const [o,l]=await Promise.all([j('/api/overview'),j('/api/enquiries')]);metrics(o.metrics||{});enquiries=l.enquiries||[];rows()}
$('#reset').onclick=async()=>{loader.classList.remove('hidden');try{await j('/api/reset',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});selected=null;$('#detail').className='empty';$('#detail').textContent='Select an enquiry to inspect its state and activity.';await load();note('Demo reset to presentation baseline')}catch(e){note(e.message)}finally{loader.classList.add('hidden')}};
(async()=>{try{config=await j('/api/config');const c=config.client||{},br=c.branding||{},name=br.brand_name||c.display_name||'Client';document.documentElement.style.setProperty('--accent',br.accent||'#26705b');$('#title').textContent=name+' Staff CRM';$('#brand').textContent='Bizi Systems · '+name;$('#mbrand').textContent=name+' CRM';await load()}catch(e){note(e.message)}finally{loader.classList.add('hidden')}})();
</script></body></html>`}

const server=http.createServer(async(req,res)=>{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);if(url.pathname==='/health')return send(res,200,{ok:true,service:'bizi-demo-web',client_key:CLIENT_KEY,package:PACKAGE});if(url.pathname==='/'||url.pathname==='/patient')return send(res,200,patientPage(),'text/html; charset=utf-8');if(url.pathname==='/crm')return send(res,200,crmPage(),'text/html; charset=utf-8');return send(res,404,'Not found','text/plain; charset=utf-8')});
server.listen(PORT,'0.0.0.0',()=>console.log('BIZI_DEMO_WEB_READY',PORT,CLIENT_KEY,PACKAGE));
